[project]
name = "neumonia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JoseLuqueC", email = "joseluque93l.lc@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
neumonia = "neumonia:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
